[flags]
rate = "2s"
retention = "10m"
battery = true
hide_table_gap = true
temperature_type = "c"

[processes]
default_tree = true

[network]
use_bytes = true

[network.interface_filter]
is_list_ignored = true
list = ["lo0", "llw.*", "anpi.*", "bridge.*", "awdl.*", "p2p.*", "ap.*"]
regex = true
case_sensitive = false
whole_word = false

[memory]
cache_memory = true

[styles]
theme = "nord"

[disk.mount_filter]
is_list_ignored = true
list = ["devfs", "/private/var/.*", "map .*"]
regex = true
case_sensitive = false
whole_word = false
