[settings]
cargo.binstall = true
experimental = true
minimum_release_age = "3d"
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "source"
status.show_tools = true
idiomatic_version_file_enable_tools = ["bun", "go", "python", "rust", "swift"]

[env]
PIP_REQUIRE_VIRTUALENV = "true"
RUSTC_WRAPPER = "sccache"
UV_PYTHON_PREFERENCE = "only-managed"
