[tools]
bun = "latest"
python = "latest"
uv = "latest"
rust = "latest"
cargo-binstall = "latest"

"github:charmbracelet/freeze" = { version = "latest" }
"pipx:sqlit-tui" = { version = "latest", extras = ["ssh"] }
"pipx:ghgrab" = { version = "latest" }

[settings]
cargo.binstall = true
experimental = true
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "source"
status.show_tools = true
