[tools]
bun = "latest"
python = "latest"
uv = "latest"
rust = "latest"
cargo-binstall = "latest"

"github:abhixdd/ghgrab" = { version = "latest" }
"pipx:sqlit-tui" = { version = "latest", extras = ["ssh"] }

[settings]
cargo.binstall = true
experimental = true
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "source"
status.show_tools = true
idiomatic_version_file_enable_tools = ["rust", "python", "bun"]
