[tools]
node = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
"pipx:sqlit-tui" = { version = "latest", extras = "ssh" }
"cargo:pdf_oxide_cli" = { version = "latest" }
"github:charmbracelet/freeze" = { version = "latest" }

[env]
_ = { path = "[./bin]" }

[settings]
npm = { package_manager = "pnpm" }
pipx = { uvx = true }
experimental = true
status = { show_tools = true }
node = { gpg_verify = false }
cargo = { binstall = true }
