[mgr]
prepend_keymap = [
  { on = ["g", "h"], run = "cd ~", desc = "Go to home" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "Go to ~/.config" },
  { on = ["g", "w"], run = "cd ~/wd", desc = "Go to ~/wd" },
  { on = ["N"], run = "create", desc = "Create file or directory" },
  { on = ["C"], run = "plugin ouch --format tar.zst", desc = "Compress with ouch" },
]
