# -----------------------------------------------------------------------------
# Language servers
# -----------------------------------------------------------------------------

[language-server.bash-language-server.config]
shellcheckPath = "shellcheck"
shfmt.path = "shfmt"

[language-server.biome-lsp-proxy]
command = "biome"
args = ["lsp-proxy"]

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start", "--stdio"]

[language-server.kdl-lsp]
command = "kdl-lsp"

[language-server.rumdl]
command = "rumdl"
args = ["server"]

[language-server.rust-analyzer]
config.check.command = "clippy"

[language-server.sqruff]
command = "sqruff"
args = ["lsp"]

[language-server.tofu-ls]
command = "tofu-ls"
args = ["serve"]

[language-server.typos]
command = "typos-lsp"

[language-server.vtsls]
config."vtsls.autoUseWorkspaceTsdk" = true
command = "vtsls"
args = ["--stdio"]

# -----------------------------------------------------------------------------
# Language
# -----------------------------------------------------------------------------

# Bash

[[language]]
name = "bash"
language-servers = ["bash-language-server", "typos"]

# CSS

[[language]]
name = "css"
language-servers = [
  { name = "vscode-css-language-server", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# Docker Compose

[[language]]
name = "docker-compose"
language-servers = [
  "yaml-language-server",
  "docker-language-server",
  "typos",
]
formatter = { command = "yamlfmt", args = ["-"] }

# Dockerfile

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server", "typos"]
formatter = { command = "dockerfmt" }

# Go

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp", "typos"]

# HCL

[[language]]
name = "hcl"
file-types = ["tf", "tofu", "hcl", "nomad"]
language-servers = ["tofu-ls", "typos"]
formatter = { command = "tofu", args = ["fmt", "-"] }

# HTML

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "biome-lsp-proxy",
  "typos",
]

# JavaScript

[[language]]
name = "javascript"
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# JSON

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# JSONC

[[language]]
name = "jsonc"
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# JSX

[[language]]
name = "jsx"
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# Just

[[language]]
name = "just"
language-servers = ["just-lsp", "typos"]
formatter = { command = "just", args = ["--fmt", "--justfile", "-"] }

# KDL

[[language]]
name = "kdl"
language-servers = ["kdl-lsp", "typos"]

# Markdown

[[language]]
name = "markdown"
language-servers = ["rumdl", "typos"]

# Python

[[language]]
name = "python"
language-servers = ["ruff", "ty", "typos"]

# Rust

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]

# SQL

[[language]]
name = "sql"
language-servers = ["sqruff", "typos"]
formatter = { command = "sqruff", args = ["fix", "-"] }

# Swift

[[language]]
name = "swift"
language-servers = ["sourcekit-lsp", "typos"]

# Terraform variables

[[language]]
name = "tfvars"
language-servers = ["tofu-ls", "typos"]
formatter = { command = "tofu", args = ["fmt", "-"] }

# TOML

[[language]]
name = "toml"
language-servers = ["tombi", "typos"]

# TSX

[[language]]
name = "tsx"
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# TypeScript

[[language]]
name = "typescript"
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome-lsp-proxy",
  "typos",
]

# YAML

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "typos"]
formatter = { command = "yamlfmt", args = ["-"] }
