[tools]
# Bash / Zsh
"npm:bash-language-server" = "latest"
shfmt = "latest"
shellcheck = "latest"

# Docker
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"go:github.com/reteps/dockerfmt" = "latest"
hadolint = "latest"

# Go
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"

# JavaScript / TypeScript
biome = "latest"
"npm:@vtsls/language-server" = "latest"

# JSON / HTML / CSS
"npm:vscode-langservers-extracted" = "latest"

# Just
"cargo:just-lsp" = "latest"

# KDL
"cargo:kdl-lsp" = "latest"
"cargo:kdlfmt" = "latest"

# Markdown
rumdl = "latest"

# OpenTofu
"github:opentofu/opentofu-ls" = "latest"

# Python
ruff = "latest"
ty = "latest"

# Spell Checker
"cargo:typos-lsp" = "latest"

# SQL
"cargo:sqruff" = "latest"

# TOML
tombi = "latest"

# YAML
"npm:yaml-language-server" = "latest"
yamlfmt = "latest"
yamllint = "latest"
