eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh --cmd cd)"
eval "$(mole completion zsh)"
eval "$(mise completion zsh)"
eval "$(fzf --zsh)"
eval "$(atuin init zsh)"
eval "$(just --completions zsh)"
eval "$(task --completion zsh)"
eval "$(rbw gen-completions zsh)"
